export const questions = [
  "What's the weirdest food combination you genuinely enjoy?",
  "If you had to fight one animal once a year, what would you pick?",
  "What's an opinion you'll defend even though everyone disagrees?",
  "What's the dumbest purchase you've ever made?",
  "What's your most useless talent?",
  "If you were arrested today, what would your friends assume you did?",
  "What TV show could you survive living in?",
  "What's your irrational fear?",
  "If your life had a loading screen tip, what would it say?",
  "What fictional character would be the worst roommate?",
  "What's the worst gift you've ever received?",
  "If you could permanently remove one word from the English language, what would it be?",
  "What's the most embarrassing song on your playlist?",
  "If your pet could talk, what's the first insult they'd throw at you?",
  "What's a hill you're willing to die on?",
  "What's something everyone pretends to like?",
  "What's the oldest thing you still own?",
  "What would your WWE entrance music be?",
  "If calories didn't exist, what are you eating every day?",
  "What's the funniest injury you've ever had?",

  "Would you rather always have to whisper or always have to yell?",
  "Would you rather have unlimited money but no internet, or unlimited internet but no money?",
  "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
  "Would you rather never eat pizza again or never eat tacos again?",
  "Would you rather sneeze glitter or cry maple syrup?",
  "Would you rather only be able to use Internet Explorer forever or dial-up internet?",
  "Would you rather have a rewind button or a pause button for life?",
  "Would you rather always have wet socks or a rock in your shoe?",
  "Would you rather only drink warm water or room-temperature soda?",
  "Would you rather win $100k or have your favorite sports team win a championship?",

  "What's the first game you ever got addicted to?",
  "Which game deserves a remake?",
  "What's your biggest gaming rage moment?",
  "Which NPC deserves to get punched?",
  "What's your comfort game?",
  "If you could live inside one game world, which one?",
  "What's a game everyone loves that you just couldn't get into?",
  "Keyboard & mouse or controller?",
  "What's the hardest boss you've beaten?",
  "Which game soundtrack is the GOAT?",
  "What's the worst microtransaction you've ever seen?",
  "If you had to play only one game for a year, what would it be?",
  "What's your gaming hot take?",
  "Which game has the best community?",
  "Which game has the worst community?",

  "If you could max one building instantly in Clash of Clans, what would you pick?",
  "What's the most satisfying troop to watch?",
  "What's your favorite Town Hall design?",
  "Which troop deserves a buff?",
  "Which troop deserves a nerf?",
  "Who's your favorite hero?",
  "What's the worst feeling in Clash of Clans?",
  "Have you ever accidentally used a Training Potion right before logging off?",
  "What's the luckiest thing that's happened to you in Clash?",
  "If you could delete one defense forever, which one?",
  "What's the funniest clan mail you've ever seen?",
  "What's worse: missing both war attacks or attacking the wrong base?",
  "What's your dream Clan Games reward?",
  "Which scenery is your favorite?",
  "Air attacks or ground attacks?",
  "Which troop would make the best roommate?",
  "If Barbarians were real, what job would they have?",
  "If you could add one troop from another game into Clash, who would it be?",
  "What's the most cursed army you've ever used?",
  "What's your favorite hero skin?",
  "If you had to permanently delete one Siege Machine, which one?",
  "Which hero would win in a fistfight with no abilities?",
  "What's your favorite Clash event Supercell has ever done?",
  "What's the funniest player name you've ever seen?",
  "If your base could talk after getting 3-starred, what would it say?",

  "Aliens arrive tomorrow. What's the first meme you show them?",
  "You have to swap lives with someone in this server. Who are you picking?",
  "If you had warning labels, what would yours say?",
  "What's your Roman Empire?",
  "If you became famous overnight, what would it be for?",
  "What's something you'd ban immediately if you became president?",
  "If your Google search history became public, how cooked are you?",
  "What's one conspiracy theory that's just funny enough to believe?",
  "What's your zombie apocalypse job?",
  "What's the weirdest compliment you've ever received?",

  "Pineapple on pizza: yes or no?",
  "Is cereal soup?",
  "Is a hot dog a sandwich?",
  "What's the most overrated fast-food chain?",
  "Fries or onion rings?",
  "What's your go-to gas station snack?",
  "What's one food everyone loves that you can't stand?",
  "If you had to eat one meal forever, what would it be?",
  "What's your most unpopular food opinion?",
  "Sweet or savory?",

  "Who in this server would survive the longest in a zombie apocalypse?",
  "Who's most likely to forget both war attacks?",
  "Who's most likely to accidentally 1-star a dip?",
  "Which member would make the best Clan Capital NPC?",
  "Who's the biggest yapper in the server?",
  "Who would win a real-life free-for-all?",
  "Which member would be the best Clash troop?",
  "Which member would accidentally start an international incident?",
  "What's the funniest thing that's happened in this server?",
  "What's one Discord quote from someone here that you'll never forget?"
];